version: '3'
services:
  redis-om:
    image: redis/redis-stack:latest
    container_name: redis-om
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    networks:
      - backend_network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Polls
    restart: always
    networks:
      - backend_network

  backend:
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    expose: 
      - 3000
    depends_on:
      - postgres
      - redis-om
    env_file:
      - ./backend/.env

    networks:
      - backend_network
      - frontend_network

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    expose: 
      - 8080
    networks:
      - frontend_network
      - backend_network

networks:
  backend_network:
  frontend_network: